name: HPCR-TerraformProvider
on: [push]
env:
  VERSION: 0.0.0
  TF_BASE: build/terraform
  PLUGIN: plugins/www.ibm.com/local/secure-execution/${VERSION}
  PREFIX: ${TF_BASE}/${PLUGIN}
  SUFFIX: terraform-provider-hpcr_v${VERSION}
jobs:
  Build-Terraform-Provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: |
          go version
          go env -w GOFLAGS=-mod=mod
          go mod tidy
          go get
          go test ./... -v
          echo ${PREFIX}
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -trimpath -o ${PREFIX}/linux_amd64/${SUFFIX}
          CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build -ldflags "-s -w" -trimpath -o ${PREFIX}/linux_s390x/${SUFFIX}
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -trimpath -o ${PREFIX}/darwin_amd64/${SUFFIX}
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -trimpath -o ${PREFIX}/windows_amd64/${SUFFIX}.exe
          find ${TF_BASE}
